feat(engine_dast): new dast scanning engine.
bancolombia/devsecops-engine-tools pull request #140
Opened 2024-05-07 23:01 UTC by russbelln

## Description

- Add new dast scanning engine
- Add the Nuclei tool as driven adapter of the new engine

## Checklist:

- [x] The pull request is complete according to the guide of [contributing](https://github.com/bancolombia/devsecops-engine-tools/blob/trunk/docs/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes

2024-05-27 14:31 UTC, russbelln commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/jwt/jwt_tool.py
> +        enc = jwt.get_unverified_header(token)["enc"]
Is used to check JWTs

2024-09-24 00:46 UTC, Gaviria9601 reviewed
- Review the comments
- update example_remote_config_local engine_core with ENGINE_DAST config
-  remove .gitkeeps
- Review the security issues sonarcloud
- update version tools/devsecops_engine_tools/version.py

2024-09-24 00:46 UTC, Gaviria9601 commented on example_remote_config_local/engine_dast/ConfigTool.json
> +        "EXTERNAL_CHECKS_GIT": "git@example.com:org/project.git/rules",
delete EXTERNAL_CHECKS_GIT, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.external_asset_name = json_data[tool].get("EXTERNAL_DIR_ASSET_NAME")
use external_asset_name to parameterise the asset name

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.use_external_checks_git = json_data[tool].get("USE_EXTERNAL_CHECKS_GIT")
delete use_external_checks_git, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.external_checks_git = json_data[tool].get("EXTERNAL_CHECKS_GIT")
delete external_checks_git, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.external_checks_save_path = json_data[tool].get("EXTERNAL_CHECKS_PATH")
I think it is not necessary to use external_checks_save_path

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.rules_all = {}
delete rules_all, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.rules_all = {}
delete rules_all, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.rules_data_type = json_data[tool].get("RULES")
delete rules_data_type, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on example_remote_config_local/engine_dast/ConfigTool.json
> +        "RULES":{}
delete RULES, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on example_remote_config_local/engine_sca/engine_container/ConfigTool.json
please do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_core/src/domain/usecases/handle_scan.py
> +        elif "engine_dast" in dict_args["tool"]:
add call to function vulnerability_management

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_core/src/infrastructure/driven_adapters/aws/s3_manager.py
please do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_core/test/infrastructure/driven_adapters/aws/test_s3_manager.py
please do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_core/test/infrastructure/driven_adapters/github/test_github_actions.py
please do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/applications/runner_iac_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/domain/model/config_tool.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/driven_adapters/checkov/checkov_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/driven_adapters/kics/kics_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/driven_adapters/kubescape/kubescape_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/helpers/file_generator_tool.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/applications/test_runner_iac_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/driven_adapters/checkov/test_checkov_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/driven_adapters/kics/test_kics_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/driven_adapters/kubescape/test_kubescape_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/helpers/test_file_generator_tool.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_secret/src/domain/usecases/set_input_core.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/domain/usecases/test_secret_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/infrastructure/driven_adapters/git_cli/test_git_run.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/infrastructure/driven_adapters/trufflehog/test_trufflehog_deserealizator.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/infrastructure/entry_points/test_entry_point_tool.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/src/domain/usecases/handle_remote_config_patterns.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/src/domain/usecases/set_input_core.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/src/infrastructure/driven_adapters/trivy_tool/trivy_deserialize_output.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/test/applications/test_runner_container_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/test/domain/usescases/test_container_sca_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/test/domain/usescases/test_handle_remote_config_patterns.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/test/domain/usescases/test_set_input_core.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/test/infrastructure/driven_adapters/prisma_cloud/test_prisma_cloud_manager_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_container/test/infrastructure/driven_adapters/trivy_tool/test_trivy_manager_scan.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_dependencies/src/domain/usecases/handle_remote_config_patterns.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_dependencies/src/domain/usecases/set_input_core.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_sca/engine_dependencies/test/domain/usecases/test_handle_remote_config_patterns.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_utilities/github/infrastructure/github_api.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_utilities/test/github/infrastructure/test_github_api.py
please, do not modify this file

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/applications/runner_dast_scan.py
> +def runner_engine_dast(dict_args, config_tool, secret_tool, devops_platform):
handle try .. except raise Exception(f"Error engine_dast : ..

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/entry_points/entry_point_dast.py
> +    except Exception as e:
not capture exception in this layer.

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/usecases/dast_scan.py
> +                dict_args["remote_config_repo"], "engine_dast/configTool.json"
update engine_dast/ConfigTool.json

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/usecases/dast_scan.py
> +                stage_pipeline="Release",
use devops_platform_gateway.get_variable("stage")

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/usecases/dast_scan.py
> +        except Exception as e:
not capture exception in this layer.

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/devops_platform_gateway.py
delete this gateway. instead use the gateway core

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/remote_config_gateway.py
delete this file, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/token_technology.py
delete this file, it not used

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +    def execute(self, target_config: NucleiConfig) -> dict:
Validate the installation https://docs.projectdiscovery.io/tools/nuclei/install

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +                print(f"Error executing nuclei: {error}")
not use print. instead use devsecops_engine_tools.engine_utilities.utils.logger_info import MyLogger

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        path_file_results = generate_file_from_tool(
do not generate file, with result_dast_scan.json is needed

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/jwt/jwt_tool.py
> +            finding_list = self.deserialize_results(result_scans)
not exists function deserialize_results. Is get_list_finding ?

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/jwt/jwt_tool.py
> +            path_file_results = generate_file_from_tool(
Update generate_file_from_tool function to use the same path_file_results of tool main

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/oauth/generic_oauth.py
> +            print("OAuth: Can't obtain access token: {0}".format(e))
do not use print, insted use logger module

2024-09-24 00:46 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/helpers/url_validator.py
delete this helper, it not used

2024-09-24 17:12 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/applications/runner_dast_scan.py
> +        checks_token=secret_tool["github_token"] if secret_tool else os.environ["GITHUB_TOKEN"],
not use os.environ["GITHUB_TOKEN"] , instead dict_args["token_external_checks"] -> secret_external_checks.split("github:")[1]
                    if "github" in secret_external_checks

2024-09-24 17:18 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        if config_tool.use_external_checks_dir == "True":
if config_tool.use_external_checks_dir is false, what would be the path ?

2024-09-24 22:17 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +            "nuclei "
validate where the nuclei tool is installed

2024-09-24 22:36 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +            result = subprocess.run(
it was validate the possible error https://github.com/orgs/projectdiscovery/discussions/1835 ?

2024-09-24 22:37 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +            if (error is not None and error != "") and self.debug == "true":
its better validate with returncode

2024-09-25 21:52 UTC, octaviovg commented on tools/requirements.txt
> +Authlib==1.3.0
Aprovechemos a actualizar a las ultimas versiones de Authlib y pyJWT que son ajustes compatibles a lo que tenemos hoy en día, hacerlo también en el requirements_test.txt

2024-09-26 19:21 UTC, russbelln commented on example_remote_config_local/engine_sca/engine_container/ConfigTool.json
File restored to baseline

2024-09-26 20:46 UTC, russbelln commented on tools/devsecops_engine_tools/engine_core/src/infrastructure/driven_adapters/aws/s3_manager.py
File restored to baseline.

2024-09-26 20:54 UTC, russbelln commented on tools/devsecops_engine_tools/engine_utilities/test/github/infrastructure/test_github_api.py
file was restored.

2024-09-26 20:57 UTC, russbelln commented on tools/devsecops_engine_tools/engine_utilities/github/infrastructure/github_api.py
file was restored.

2024-09-26 21:21 UTC, russbelln commented on tools/devsecops_engine_tools/engine_core/test/infrastructure/driven_adapters/aws/test_s3_manager.py
file was restored

2024-09-26 21:22 UTC, russbelln commented on tools/devsecops_engine_tools/engine_core/test/infrastructure/driven_adapters/github/test_github_actions.py
File was restored.

2024-09-26 21:23 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/applications/runner_iac_scan.py
File was restored.

2024-09-26 21:24 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/domain/model/config_tool.py
File was restored.

2024-09-26 21:26 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/driven_adapters/checkov/checkov_deserealizator.py
File was restored.

2024-09-26 21:27 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/driven_adapters/kics/kics_deserealizator.py
File was restored.

2024-09-26 21:29 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/driven_adapters/kubescape/kubescape_deserealizator.py
File was restored.

2024-09-26 21:30 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/src/infrastructure/helpers/file_generator_tool.py
File was restored.

2024-09-26 21:33 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/applications/test_runner_iac_scan.py
File was restored.

2024-09-26 21:34 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/driven_adapters/checkov/test_checkov_deserealizator.py
File was restored.

2024-09-26 21:35 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/driven_adapters/kics/test_kics_deserealizator.py
File was restored.

2024-09-26 21:37 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/driven_adapters/kubescape/test_kubescape_deserealizator.py
File was restored.

2024-09-26 21:39 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_iac/test/infrastructure/helpers/test_file_generator_tool.py
File was restored.

2024-09-26 21:41 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_secret/src/domain/usecases/set_input_core.py
File was restored.

2024-09-26 21:41 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/domain/usecases/test_secret_scan.py
File was restored.

2024-09-26 21:45 UTC, russbelln commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/token_technology.py
File was deleted.

2024-09-26 21:46 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/infrastructure/entry_points/test_entry_point_tool.py
File was restored.

2024-09-26 21:48 UTC, russbelln commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/devops_platform_gateway.py
File was deleted.

2024-09-26 21:49 UTC, russbelln commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/remote_config_gateway.py
File was deleted.

2024-09-26 21:52 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/infrastructure/driven_adapters/git_cli/test_git_run.py
File was restored.

2024-09-26 21:53 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/infrastructure/driven_adapters/trufflehog/test_trufflehog_deserealizator.py
File was restored.

2024-09-26 21:54 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sca/engine_container/src/domain/usecases/handle_remote_config_patterns.py
File was restored.

2024-09-26 21:56 UTC, russbelln commented on tools/devsecops_engine_tools/engine_sca/engine_container/src/domain/usecases/set_input_core.py
File was restored.

2024-09-27 03:52 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_utilities/github/models/GithubPredefinedVariables.py
> -import os
this file is not modified

2024-09-27 03:53 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_sca/engine_dependencies/src/domain/usecases/handle_remote_config_patterns.py
> -import re
this file is not modified

2024-09-27 03:56 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_sast/engine_secret/test/domain/usecases/test_secret_scan.py
> -import unittest
this file is not modified

2024-09-27 03:59 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_core/src/applications/runner_engine_core.py
> +        help="Engine DAST Api or Web Application configuration file path"
be more specific in the help, remember is an opensource tool

2024-09-27 12:24 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/gateways/__init__.py
delete file

2024-09-27 12:41 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/domain/usecases/dast_scan.py
> +from devsecops_engine_tools.engine_dast.src.domain.model.gateways.devops_platform_gateway import (
this gateway dont exist

2024-09-27 12:55 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/domain/usecases/dast_scan.py
> +            if len(self.other_tools) > 0:
Russ some doubts here, which other tool we can run here, con you bring me an example? how to secure that tool need the same configuration like nuclei?

2024-09-27 15:09 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/http/client/auth_client.py
> +        self.client_secrets: str = security_auth.get("client_secret")
only secret, delete the "s". An another question, is necesary implement gateway here? the implmentation does not anything

2024-09-27 15:17 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/jwt/jwt_object.py
> +        self.payload: dict = {}
why is necessary payload if you have all the internal values defined previously?

2024-09-27 15:24 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/jwt/jwt_tool.py
> +    def verify_jws_alg(self, token):
this method is duplicated

2024-09-27 15:42 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/jwt/jwt_tool.py
> +        if alg in self.BAD_JWT_ALG: #Is vulnerable
if it´s not vulnerable what is the return?

2024-09-27 16:19 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        self.debug: str = os.environ.get("DEBUG", "false")
is good idea, leave this parameter from external config_tool?

2024-09-27 17:06 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/test/infrastructure/driven_adapters/jwt/test_jwt_object.py
delete file

2024-09-27 20:02 UTC, octaviovg commented on tools/devsecops_engine_tools/engine_dast/test/infrastructure/helpers/test_dast_file_generator_tool.py
> +        self.assertIsNotNone(result)
improve the assert. be more specific

2024-09-27 20:03 UTC, octaviovg approved these changes

2024-09-27 20:04 UTC, octaviovg requested changes
Validate comments

2024-10-18 22:30 UTC, Gaviria9601 commented on example_remote_config_local/engine_dast/ConfigTool.json
Update the file example_remote_config_local/engine_core/ConfigTool.json with the EXTRA_TOOLS property in the ENGINE_DAST block

2024-10-18 22:32 UTC, Gaviria9601 commented on .gitignore
Delete .gitkeep files where it is not needed

2024-10-18 22:42 UTC, Gaviria9601 commented on example_remote_config_local/engine_dast/ConfigTool.json
> +        "EXCLUSIONS_PATH": "/engine_dast/Exclusions.json",
delete EXCLUSIONS_PATH, it not used

2024-10-18 22:43 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/domain/model/config_tool.py
> +        self.exclusions_path = json_data[tool].get("EXCLUSIONS_PATH")
delete exclusions_path, it not used

2024-10-18 22:54 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        result = subprocess.run(command, capture_output=True, shell=True)
check the installation with subprocess.run( ["nuclei", "./trivy"] and handle the response with the return code.

2024-10-18 22:59 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        download = subprocess.run(
download with requests.get and release according to platform.system()

2024-10-18 23:00 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        unzip = subprocess.run(
instead use Utils.unzip_file

2024-10-18 23:01 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +        make_exe = subprocess.run(
run it only with unix operating systems

2024-10-18 23:03 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +            "nuclei "
Validate with the response of which

2024-10-21 19:10 UTC, Gaviria9601 reviewed
Review new comments

2024-10-21 19:10 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/helpers/file_generator_tool.py
> +    if tool.lower() == "nuclei":
nuclei not it necesary. If this is for JWT, use a generic format or SARIF to send to defect dojo

2024-10-21 19:10 UTC, Gaviria9601 commented on tools/devsecops_engine_tools/engine_dast/src/infrastructure/driven_adapters/nuclei/nuclei_tool.py
> +            return None
reurn [], None

2025-02-03 21:35 UTC, closed without merging