engine_secret only pull request files
bancolombia/devsecops-engine-tools pull request #88
Opened 2024-03-05 03:41 UTC by cajlopezor

## Description

The engine_secret task is modified in which only the pull request files will be evaluated

### Fix
*How does someone fix the issue in code and/or in runtime?*
The engine_secret task is modified in which only the pull request files will be evaluated

## Checklist:

- [x] The pull request is complete according to the guide of [contributing](https://github.com/bancolombia/NU0429001_devsecops_engine/blob/trunk/docs/CONTRIBUTING.md) of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my feature, policy, or fix is effective and works
- [x] New and existing tests pass locally with my changes

2024-03-06 17:09 UTC, octaviovg requested changes
En general, ajustar las unitarias que ninguna esta validando nada realmente.

2024-03-12 16:17 UTC, Gaviria9601 submitted a review, later dismissed

2024-03-12 17:48 UTC, octaviovg requested changes

2024-03-14 14:08 UTC, octaviovg approved these changes

2024-03-14 14:10 UTC, merged